parameters:
    cygnus_api_suite.curl.kernel.class: Cygnus\ApiSuiteBundle\RemoteKernel\Curl\RemoteKernel
    cygnus_api_suite.curl.client.class: Cygnus\ApiSuiteBundle\RemoteKernel\Curl\Client
    cygnus_api_suite.curl.processor.header.class: Cygnus\ApiSuiteBundle\RemoteKernel\Curl\Processor\ResponseHeaderProcessor
    cygnus_api_suite.curl.processor.body.class: Cygnus\ApiSuiteBundle\RemoteKernel\Curl\Processor\ResponseBodyProcessor
    cygnus_api_suite.api_client.google.geocode.class: Cygnus\ApiSuiteBundle\ApiClient\Google\ApiClientGeoCode
    cygnus_api_suite.api_client.omeda.class: Cygnus\ApiSuiteBundle\ApiClient\Omeda\ApiClientOmeda
    cygnus_api_suite.api_client.openx.class: Cygnus\ApiSuiteBundle\ApiClient\OpenX\ApiClientOpenX
    cygnus_api_suite.api_client.gigya.class: Cygnus\ApiSuiteBundle\ApiClient\Gigya\ApiClientGigya
    cygnus_api_suite.api_client.exact_target.class: Cygnus\ApiSuiteBundle\ApiClient\ExactTarget\ApiClientExactTarget
    cygnus_api_suite.api_client.mailchimp.class: Cygnus\ApiSuiteBundle\ApiClient\Mailchimp\ApiClientMailchimp
    cygnus_api_suite.api_client.brightcove.class: Cygnus\ApiSuiteBundle\ApiClient\Brightcove\ApiClientBrightcove
    cygnus_api_suite.api_client.base2.class: Cygnus\ApiSuiteBundle\ApiClient\Base2\ApiClientBase2
    cygnus_api_suite.api_client.media.class: Cygnus\ApiSuiteBundle\ApiClient\Media\ApiClientMedia
    cygnus_api_suite.api_client.merrick.class: Cygnus\ApiSuiteBundle\ApiClient\Merrick\ApiClientMerrick
    cygnus_api_suite.oauth.kernel.class: Cygnus\ApiSuiteBundle\RemoteKernel\OAuth1a\RemoteKernel

services:
    cygnus_api_suite.curl.header_processor:
        class: %cygnus_api_suite.curl.processor.header.class%
    cygnus_api_suite.curl.body_processor:
        class: %cygnus_api_suite.curl.processor.body.class%
    cygnus_api_suite.curl.client:
        class: %cygnus_api_suite.curl.client.class%
        arguments: ["@cygnus_api_suite.curl.header_processor", "@cygnus_api_suite.curl.body_processor", "@logger"]
        tags:
            - { name: monolog.logger, channel: api_suite}

    cygnus_api_suite.abstract.kernel:
        abstract: true
        arguments: [ "@cygnus_api_suite.curl.client" ]

    cygnus_api_suite.curl.kernel:
        parent: cygnus_api_suite.abstract.kernel
        class: %cygnus_api_suite.curl.kernel.class%

    cygnus_api_suite.oauth.kernel:
        parent: cygnus_api_suite.abstract.kernel
        class: %cygnus_api_suite.oauth.kernel.class%

    cygnus_api_suite.api_client.abstract:
        abstract: true
        calls:
             - [setRemoteHttpKernel, ["@cygnus_api_suite.curl.kernel"]]

    cygnus_api_suite.api_client.mailchimp:
        class: %cygnus_api_suite.api_client.mailchimp.class%
        parent: cygnus_api_suite.api_client.abstract

    cygnus_api_suite.api_client.google.geocode:
        class: %cygnus_api_suite.api_client.google.geocode.class%
        parent: cygnus_api_suite.api_client.abstract

    cygnus_api_suite.api_client.gigya:
        class: %cygnus_api_suite.api_client.gigya.class%

    cygnus_api_suite.api_client.exact_target:
        class: %cygnus_api_suite.api_client.exact_target.class%
        calls:
            - [setLogger, ["@logger"]]
        tags:
            - { name: monolog.logger, channel: api_suite.exact_target}

    cygnus_api_suite.api_client.omeda:
        class: %cygnus_api_suite.api_client.omeda.class%
        parent: cygnus_api_suite.api_client.abstract

    cygnus_api_suite.api_client.openx:
        class: %cygnus_api_suite.api_client.openx.class%
        parent: cygnus_api_suite.api_client.abstract
        calls:
             - [setRemoteHttpKernel, ["@cygnus_api_suite.oauth.kernel"]]


    cygnus_api_suite.api_client.base2:
        class: %cygnus_api_suite.api_client.base2.class%
        parent: cygnus_api_suite.api_client.abstract
        tags:
            - { name: cygnus_api_suite.cacheable }

    cygnus_api_suite.api_client.media:
        class: %cygnus_api_suite.api_client.media.class%
        parent: cygnus_api_suite.api_client.abstract

    cygnus_api_suite.api_client.merrick:
        class: %cygnus_api_suite.api_client.merrick.class%
        parent: cygnus_api_suite.api_client.abstract
        tags:
            - { name: cygnus_api_suite.cacheable }

    cygnus_api_suite.api_client.brightcove:
        class: %cygnus_api_suite.api_client.brightcove.class%
        parent: cygnus_api_suite.api_client.abstract

    cygnus_api_suite.api_client.varnish:
        class: Cygnus\ApiSuiteBundle\ApiClient\Varnish\ApiClientVarnish
        parent: cygnus_api_suite.api_client.abstract
